# Generated by Django 5.1.1 on 2024-11-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('engineering', 'Engineering'), ('science', 'Science')], max_length=20)),
                ('image', models.ImageField(upload_to='courses/')),
                ('description', models.TextField(default='Course description coming soon')),
                ('duration', models.CharField(default='48 hours', max_length=50)),
                ('instructor_name', models.CharField(max_length=100)),
                ('instructor_title', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('students_enrolled', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
