# Generated by Django 4.2.16 on 2024-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_students_enrolled_course_lessons_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter YouTube video URL'),
        ),
    ]
