# Generated by Django 4.2.16 on 2024-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_course_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter YouTube video URL', null=True),
        ),
    ]
