# Generated by Django 4.2.16 on 2024-11-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_description',
            field=models.TextField(blank=True, help_text='Enter YouTube Description', max_length=200, null=True),
        ),
    ]
